// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eetbqplrrpfakagerrag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVldGJxcGxycnBmYWthZ2VycmFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxNTQ1NDksImV4cCI6MjA1ODczMDU0OX0.br1pugBZLUCTNoYHy5dS5dj4um7wYzwAsWpNmrnmInI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);